### REGISTERING A USER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username" : "testUser2",
    "password" : "12312sd3" 
}

### LOGGIN-IN A USER
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username" : "testUser2",
    "password" : "12312sd3"
}

### REMOVE 
DELETE http://localhost:5000/auth/remove/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzg1MjU3NjYwLCJleHAiOjE3ODUzNDQwNjB9.eY4oCGe74lf4OwVfSGK3Epmbd4dIaajt0pJ8ndODONY

### CREATE NOTE
POST http://localhost:5000/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzg1NDM0MDIyLCJleHAiOjE3ODU1MjA0MjJ9.1UvAWGbz_tEUVFleK8iulkHXiw8W0nCOrgFCjoT6NsI

{
    "title" : "another note",
    "content" : "ipsom sth i dont know what to put here"
}


### GET NOTES (v2)
GET http://localhost:5000/notes?page=1&limit=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzg1NDM0MDIyLCJleHAiOjE3ODU1MjA0MjJ9.1UvAWGbz_tEUVFleK8iulkHXiw8W0nCOrgFCjoT6NsI

### SEARCH NOTES 
GET http://localhost:5000/notes/s?search=image
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzg1NDM0MDIyLCJleHAiOjE3ODU1MjA0MjJ9.1UvAWGbz_tEUVFleK8iulkHXiw8W0nCOrgFCjoT6NsI


### UPDATE A NOTE
PUT http://localhost:5000/notes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzg1MzEwNDk3LCJleHAiOjE3ODUzOTY4OTd9.ZNIrWkxj7lF7HwTqlPmvlERkbkDwov23AkJIwWpeSZs

{
    "title" : "my updatedddd title",
    "content" : "this content has been updated"
}

### DELETE A NOTE 
DELETE http://localhost:5000/notes/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzg1NDI5ODg0LCJleHAiOjE3ODU1MTYyODR9._EVOYF93g24-wE334YRPf262VoqXqm1IBB2YO1YkKTA

### create note with image
POST http://localhost:5000/notes
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNzg1NDI5ODg0LCJleHAiOjE3ODU1MTYyODR9._EVOYF93g24-wE334YRPf262VoqXqm1IBB2YO1YkKTA

--boundary123
Content-Disposition: form-data; name="title"

My image note

--boundary123
Content-Disposition: form-data; name="content"

This note has an image

--boundary123
Content-Disposition: form-data; name="image"; filename="tester.png"
Content-Type:image/png

< ./tester.png

--boundary123--

